### ISSUE TITLE
klasy

### ISSUE THREAD

**Issue by malinowakrew** [phajder-databases/db2020-project-muzeum#1]
Jakie klasy zadeklarować w naszym projekcie?

**Comment by phajder** [comment]
Jeśli pytacie o klasy z punktu widzenia OOP, to na pewno encyjne. Są to klasy odzwierciedlające rekordy w tabeli.
Jeżeli chodzi o inne - to zasadniczo nie musicie tworzyć żadnych. Cała apka może być oparta o programowanie proceduralne.
Jako że do mieliście do tej pory tylko obiektówkę a Java i webówka przed Wami, nie upieram się przy konkretnych podejściach.
