### ISSUE TITLE
SQL i APP podział

### ISSUE THREAD

**Issue by malinowakrew** [phajder-databases/db2020-project-muzeum#2]
Czy możemy mieć też pytanie co do odpowiedniego podziału projektu. Każde z nas inaczej widzi zdefiniowany podział na zapytania sql i kod źródłowy. Czy obecny podział jest poprawny? Czy powinniśmy go zmiemić?

**Comment by malinowakrew** [comment]
Pytamy o branch baza.

**Comment by phajder** [comment]
Jest ok. Uważajcie tylko na powtórzenia kodu.
